### ISSUE TITLE
Add explanations to functions 

### ISSUE THREAD

**Issue by talentedmrjones** [CMS-Enterprise/ztmf#39]
use `functionscores.notes`

**Comment by eschwein-usds** [comment]
<img width="1281" alt="Elizabeth's Dreams" src="https://github.com/CMS-Enterprise/ztmf/assets/69164359/731efa31-a1c6-4c15-b764-9e700f60f821">
Add a column to the right of the Score to display the Notes associated with the Pillar/Function.
The diagram also shows a couple of other changes that I will make into separate issues.
