### ISSUE TITLE
Add the Function Description

### ISSUE THREAD

**Issue by eschwein-usds** [CMS-Enterprise/ztmf#41]
On the page that displays the Functions for an entire pillar, add a way for the user to see the Functions.description for each function.

Options:
- Print it underneath the Function name
- Make a tool tip that the user can hover over
- Your option here
![Uploading Elizabeth's Dreams.png…]()

**Comment by ATNoblis** [comment]
Where can I find the description for each of the pillar functions for the tool tip?
